#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from os.path import basename
from datetime import datetime
from hashlib import md5

#=============================================================================
def main():
    txt_fn, mod_name = sys.argv[1:]

    now = datetime.now().replace(microsecond=0)

    content = open(txt_fn).read()
    output  = "!-----------------------------------------------------------------------------!\n"
    output += "!   CP2K: A general program to perform molecular dynamics simulations         !\n"
    output += "!   Copyright (C) 2000 - %d  CP2K developers group                          !\n"%now.year
    output += "!-----------------------------------------------------------------------------!\n"
    output += "\n"
    output += "! *****************************************************************************\n"
    output += "!> \\brief Generated by txt2f90.py\n"
    output += "!> \\author Ole Schuett\n"
    output += "! *****************************************************************************\n"
    output += "\n"
    output += "MODULE %s\n"%mod_name
    output += "IMPLICIT NONE\n"
    output += "PRIVATE\n"
    output += "PUBLIC :: M_filename, M_date, M_md5sum, M_get_text\n".replace("M", mod_name)
    output += "\n"
    output += "CHARACTER(LEN=*), PARAMETER :: %s_filename = '%s'\n"%(mod_name, basename(txt_fn))
    output += "CHARACTER(LEN=*), PARAMETER :: %s_date = '%s'\n"%(mod_name, now.isoformat())
    output += "CHARACTER(LEN=*), PARAMETER :: %s_md5sum = '%s'\n"%(mod_name, md5(content).hexdigest())
    output += "CHARACTER(LEN=1), PARAMETER :: nl = ACHAR(10) !newline\n"
    output += "\n"
    output += "CHARACTER(len=*), PARAMETER :: block00000 = ''"

    lines = content.split("\n")

    #lines = [l for l in lines if not l.startswith("#")]
    #lines = [l for l in lines if len(l.strip()) > 0]

    for line_no, line in enumerate(lines, start=1):
        if(line_no%100 == 0):
            b = line_no/100
            output += "\n\nCHARACTER(len=*), PARAMETER :: block%.5d = block%.5d"%(b, b-1)
        output += "//&\n '%s'"%escape(line[:100])
        for i in range(1,len(line)/100 + 1):
            output += "//&\n   '%s'"%escape(line[i*100:(i+1)*100])
        if(line_no<len(lines)): output += "//nl"

    #output += "\n\nCHARACTER(len=*), PARAMETER :: %s_text = block%.5d"%(mod_name,len(lines)/100)

    output += "\n\nCONTAINS\n\n"
    output += "! *****************************************************************************\n"
    output += "!> \\brief Returns content of the file.\n"
    output += "!>        Wrapping this in a function allows to add compression someday.\n"
    output += "!> \\author Ole Schuett\n"
    output += "! *****************************************************************************\n"
    output += "FUNCTION %s_get_text() RESULT(text)\n"%mod_name
    output += "  CHARACTER(LEN=LEN(block%.5d)) :: text\n"%(len(lines)/100)
    output += "  text = block%.5d\n"%(len(lines)/100)
    output += "END FUNCTION\n"

    output  += "\nEND MODULE %s\n"%mod_name
    print output

#=============================================================================
def escape(s):
    return s.replace("'", "'//\"'\"//'")

main()
#EOF
